age = int (input("Enter your age"))
print(age)
print(type(age))
name = input("Enter your name")
print(name)
print(type(name))
percent = float(input("Enter your percentage"))
print(percent)
print(type(percent))
